import { test, expect } from "bun:test";
import { BEGIN, END, hasBlock, rows, withBlock, withoutBlock } from "../src/menu.ts";

// A menu file shaped like the real one: comments, and a neighbour's block that
// must survive everything omastoic does.
const menu = `{
  // Extend the Quickshell Omarchy menu with JSONC.
  //
  // "personal": {"icon":"","label":"Personal"},

  // >>> omadoist:begin — generated by \`omadoist sync\`
  "todoist": {"icon":"","label":"Todoist"},
  // <<< omadoist:end
}
`;

test("the block goes in just inside the closing brace", () => {
  const next = withBlock(menu);
  expect(hasBlock(next)).toBe(true);
  expect(next.trimEnd().endsWith("}")).toBe(true);
  expect(next.indexOf(BEGIN)).toBeGreaterThan(next.indexOf("omadoist:end"));
});

test("comments and other tools' blocks survive", () => {
  const next = withBlock(menu);
  expect(next).toContain("// Extend the Quickshell Omarchy menu with JSONC.");
  expect(next).toContain("omadoist:begin");
  expect(next).toContain(`"todoist"`);
  expect(next).toContain(`"personal"`);
});

test("the rows extend Omarchy's own screensaver submenu", () => {
  for (const row of rows()) expect(row).toContain(`"style.screensaver.`);
  expect(rows().join("\n")).toContain(`"checked":"omarchy-toggle-enabled omastoic"`);
  expect(rows().join("\n")).toContain(`"action":"omastoic toggle"`);
});

test("installing twice leaves one block, not two", () => {
  const once = withBlock(menu);
  const twice = withBlock(once);
  expect(twice).toBe(once);
  expect(twice.split(BEGIN).length - 1).toBe(1);
  expect(twice.split(END).length - 1).toBe(1);
});

test("a changed set of rows replaces the old ones in place", () => {
  const before = withBlock(menu);
  const after = withBlock(before, [`  "style.screensaver.stoics": {"label":"Stoics"},`]);
  expect(after.split(BEGIN).length - 1).toBe(1);
  expect(after).toContain(`{"label":"Stoics"}`);
  expect(after).not.toContain("stoics-show");
});

test("removing the block restores the file it was added to", () => {
  expect(withoutBlock(withBlock(menu))).toBe(menu);
});

test("removing is safe when there is no block", () => {
  expect(withoutBlock(menu)).toBe(menu);
  expect(hasBlock(menu)).toBe(false);
});

test("a file with no closing brace is left untouched", () => {
  const broken = "// half a menu\n";
  expect(withBlock(broken)).toBe(broken);
});

test("the block survives a round trip through an empty menu", () => {
  const empty = "{\n}\n";
  const added = withBlock(empty);
  expect(hasBlock(added)).toBe(true);
  expect(withoutBlock(added)).toBe(empty);
});
