// Rows for the Omarchy menu, kept inside a marked block.
//
// ~/.config/omarchy/extensions/omarchy-menu.jsonc is the user's file: it has
// comments, and other tools (omadoist, say) keep blocks of their own in it. So
// it is edited as text between markers, never parsed and re-serialised — that
// would throw away every comment and every neighbour's block.

export const BEGIN = "// >>> omastoic:begin";
export const END = "// <<< omastoic:end";

const HEADER = `  ${BEGIN} — generated by \`omastoic setup\`; edits inside this block are overwritten`;
const FOOTER = `  ${END}`;

/**
 * Rows next to Omarchy's own Edit Text, Set From Image and Restore Default.
 * Stoics is the on/off; Configure opens the author and interval picker.
 */
export function rows(): string[] {
  // Hide unless the plugin is actually on disk. `omarchy plugin remove` deletes
  // the folder but used to leave these rows pointing at a missing binary.
  const installed = `[[ -f ~/.config/omarchy/plugins/omastoic/manifest.json ]]`;
  return [
    `  "style.screensaver.stoics": {"icon":"󱄄","label":"Stoics","description":"Rotate cited Stoic quotes on the screensaver","aliases":["stoic","stoics"],"when":"${installed}","checked":"omarchy-toggle-enabled omastoic","action":"omastoic toggle"},`,
    `  "style.screensaver.configure": {"icon":"","label":"Configure","description":"Choose which Stoics appear, and seconds between quotes","when":"${installed}","action":"omarchy-launch-tui omastoic config"},`,
  ];
}

// Swallow the blank line the block is inserted with, so adding and removing it
// leaves the file byte-for-byte as it was found.
const blockPattern = new RegExp(
  `(?:\\r?\\n)*[ \\t]*${escape(BEGIN)}[\\s\\S]*?${escape(END)}[ \\t]*(?=\\r?\\n|$)`,
);

function escape(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** The menu file with omastoic's block inserted, or refreshed where it already is. */
export function withBlock(source: string, lines = rows()): string {
  const block = [HEADER, ...lines, FOOTER].join("\n");

  if (blockPattern.test(source)) return source.replace(blockPattern, `\n\n${block}`);

  // Otherwise land it just inside the final closing brace, where the menu's own
  // rows end. A file without one is not a menu we understand; leave it alone.
  const close = source.lastIndexOf("}");
  if (close < 0) return source;

  const before = source.slice(0, close).replace(/\s*$/, "");
  const after = source.slice(close);
  return `${before}\n\n${block}\n${after}`;
}

/** The menu file with omastoic's block taken back out, leaving everything else. */
export function withoutBlock(source: string): string {
  return source.replace(blockPattern, "");
}

export function hasBlock(source: string): boolean {
  return blockPattern.test(source);
}
