// Rows for the Omarchy menu, kept inside a marked block.
//
// ~/.config/omarchy/extensions/omarchy-menu.jsonc is the user's file: it has
// comments, and other tools (omadoist, say) keep blocks of their own in it. So
// it is edited as text between markers, never parsed and re-serialised — that
// would throw away every comment and every neighbour's block.

export const BEGIN = "// >>> omastoic:begin";
export const END = "// <<< omastoic:end";

const HEADER = `  ${BEGIN} — generated by \`omastoic install\`; edits inside this block are overwritten`;
const FOOTER = `  ${END}`;

/**
 * The rows omastoic contributes. They extend Omarchy's own `style.screensaver`
 * submenu rather than opening a menu of their own, so switching screensavers
 * stays where Omarchy already put it — next to Edit Text, Set From Image and
 * Restore Default.
 */
export function rows(): string[] {
  return [
    `  "style.screensaver.stoics": {"icon":"󱄄","label":"Stoics","description":"Marcus Aurelius, Seneca, Epictetus and the founders of the school","aliases":["stoic","stoics"],"checked":"omarchy-toggle-enabled omastoic","action":"omastoic toggle"},`,
    `  "style.screensaver.stoics-show": {"icon":"󰑐","label":"Show a Stoic","when":"omarchy-toggle-enabled omastoic","action":"omastoic preview"},`,
  ];
}

// Swallow the blank line the block is inserted with, so adding and removing it
// leaves the file byte-for-byte as it was found.
const blockPattern = new RegExp(
  `(?:\\r?\\n)*[ \\t]*${escape(BEGIN)}[\\s\\S]*?${escape(END)}[ \\t]*(?=\\r?\\n|$)`,
);

function escape(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** The menu file with omastoic's block inserted, or refreshed where it already is. */
export function withBlock(source: string, lines = rows()): string {
  const block = [HEADER, ...lines, FOOTER].join("\n");

  if (blockPattern.test(source)) return source.replace(blockPattern, `\n\n${block}`);

  // Otherwise land it just inside the final closing brace, where the menu's own
  // rows end. A file without one is not a menu we understand; leave it alone.
  const close = source.lastIndexOf("}");
  if (close < 0) return source;

  const before = source.slice(0, close).replace(/\s*$/, "");
  const after = source.slice(close);
  return `${before}\n\n${block}\n${after}`;
}

/** The menu file with omastoic's block taken back out, leaving everything else. */
export function withoutBlock(source: string): string {
  return source.replace(blockPattern, "");
}

export function hasBlock(source: string): boolean {
  return blockPattern.test(source);
}
